export const FLOW_NODE_TYPES = [
  'static_message',
  'end',
  'handler',
  'prompt_and_branch',
  'set_state',
  'capture_text',
  'capture_number',
  'capture_phone_generic',
  'capture_phone',
  'capture_date',
  'capture_time',
  'capture_purpose',
  'capture_property_type',
  'capture_price_min',
  'capture_price_max',
  'capture_bedrooms',
  'capture_city',
  'capture_neighborhood',
  'execute_search',
  'execute_vehicle_search',
  'show_property_card',
  'property_feedback_decision',
  'refinement_decision',
] as const;

export type FlowNodeType = (typeof FLOW_NODE_TYPES)[number];

export const FLOW_NODE_TYPE_LABELS: Record<FlowNodeType, string> = {
  static_message: 'Mensagem (fixa)',
  end: 'Encerrar',
  handler: 'Ação (handler)',
  prompt_and_branch: 'Pergunta + rotas (ramificação)',
  set_state: 'Atualizar estado',
  capture_text: 'Capturar texto',
  capture_number: 'Capturar número',
  capture_phone_generic: 'Capturar telefone',
  capture_phone: 'Capturar telefone (imóveis)',
  capture_date: 'Capturar data (imóveis)',
  capture_time: 'Capturar horário (imóveis)',
  capture_purpose: 'Capturar objetivo (imóveis)',
  capture_property_type: 'Capturar tipo de imóvel (imóveis)',
  capture_price_min: 'Capturar preço mín. (imóveis)',
  capture_price_max: 'Capturar preço máx. (imóveis)',
  capture_bedrooms: 'Capturar quartos (imóveis)',
  capture_city: 'Capturar cidade (imóveis)',
  capture_neighborhood: 'Capturar bairro (imóveis)',
  execute_search: 'Buscar imóveis (catálogo)',
  execute_vehicle_search: 'Buscar veículos (catálogo)',
  show_property_card: 'Mostrar card do imóvel',
  property_feedback_decision: 'Decisão: feedback do imóvel',
  refinement_decision: 'Decisão: refinamento',
};
