"""tenant_active_flag

Revision ID: 878dda9ee4a9
Revises: d7c1f4f9e2a0
Create Date: 2026-01-02 20:44:08.261752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878dda9ee4a9'
down_revision: Union[str, Sequence[str], None] = 'd7c1f4f9e2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###
