name: Frontend CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  ui:
    name: UI (Vite/React) Lint/Typecheck/Test/Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/ui/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npx tsc -v && npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
